# Generated by Django 5.2.8 on 2025-11-15 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('key',)},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='problem',
            name='allowed_languages',
            field=models.ManyToManyField(blank=True, help_text='If empty, all languages are allowed for this problem.', related_name='problems', to='judge.language'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='judge_submi_user_id_9d8d20_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status'], name='judge_submi_problem_fb9c89_idx'),
        ),
    ]
