# Generated by Django 5.2.9 on 2025-12-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_language_options_alter_problem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ac', 'Accepted'), ('wa', 'Wrong Answer'), ('tle', 'Time Limit'), ('mle', 'Memory Limit'), ('re', 'Runtime Error'), ('ce', 'Compile Error')], default='queued', max_length=20),
        ),
    ]
