# Generated by Django 6.0 on 2025-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.IntegerField(default=512),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit_ms',
            field=models.IntegerField(default=30000),
        ),
    ]
