# Generated by Django 6.0 on 2025-12-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_remove_problem_statement_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.IntegerField(default=256),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit_ms',
            field=models.IntegerField(default=5000),
        ),
    ]
