# Generated by Django 6.0 on 2025-12-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_alter_problem_memory_limit_mb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='version',
        ),
    ]
