# Generated by Django 6.0 on 2025-12-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_slug_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='score',
        ),
    ]
