# Generated by Django 6.0 on 2025-12-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Untitled Quiz', max_length=200),
        ),
    ]
