# Generated by Django 6.0 on 2025-12-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quiz_lesson_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
