# Generated by Django 6.0 on 2025-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
