# Generated by Django 6.0 on 2025-12-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_quizattempt_score_quizattempt_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
