# Generated by Django 6.0 on 2025-12-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_quizattempt_quiz_remove_quizattempt_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='is_answer',
        ),
    ]
