# Generated by Django 6.0 on 2025-12-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_rename_is_correct_choice_is_answer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_answer', True)), fields=('question',), name='unique_answer_per_question'),
        ),
    ]
